using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace PTSL.Ovidhan.Common.Enum
{

    public enum Country
    {
        [Display(Name = "Afghanistan")] AF = 1,
        [Display(Name = "Albania")] AX = 2,
        [Display(Name = "Algeria")] AL = 3,
        [Display(Name = "American Samoa")] DZ = 4,
        [Display(Name = "Andorra")] AS = 5,
        [Display(Name = "Angola")] AD = 6,
        [Display(Name = "Anguilla")] AO = 7,
        [Display(Name = "Antarctica")] AI = 8,
        [Display(Name = "Antigua and Barbuda")] AQ = 9,
        [Display(Name = "Argentina")] AG = 10,
        [Display(Name = "Armenia")] AR = 11,
        [Display(Name = "Aruba")] AM = 12,
        [Display(Name = "Ascension Island")] AW = 13,
        [Display(Name = "Australia")] ASC = 14,
        [Display(Name = "Austria")] AU = 15,
        [Display(Name = "Azerbaijan")] AT = 16,
        [Display(Name = "Bahamas")] AZ = 17,
        [Display(Name = "Bahrain")] BS = 18,
        [Display(Name = "Bangladesh")] BH = 19,
        [Display(Name = "Barbados")] BD = 20,
        [Display(Name = "Belarus")] BB = 21,
        [Display(Name = "Belgium")] BY = 22,
        [Display(Name = "Belize")] BE = 23,
        [Display(Name = "Benin")] BZ = 24,
        [Display(Name = "Bermuda")] BJ = 25,
        [Display(Name = "Bhutan")] BM = 26,
        [Display(Name = "Bolivia")] BT = 27,
        [Display(Name = "Bosnia and Herzegovina")] BO = 28,
        [Display(Name = "Botswana")] BA = 29,
        [Display(Name = "Bouvet Island")] BW = 30,
        [Display(Name = "Brazil")] BV = 31,
        [Display(Name = "British Indian Ocean Territory")] BR = 32,
        [Display(Name = "Brunei Darussalam")] BQ = 33,
        [Display(Name = "Bulgaria")] BUL = 34,
        [Display(Name = "Burkina Faso")] BF = 35,
        [Display(Name = "Burundi")] BG = 36,
        [Display(Name = "Cambodia")] CAM = 37,
        [Display(Name = "Cameroon")] BI = 38,
        [Display(Name = "Canada")] KH = 39,
        [Display(Name = "Cape Verde")] CM = 40,
        [Display(Name = "Cayman Islands")] CA = 41,
        [Display(Name = "Central African Republic")] CAR = 42,
        [Display(Name = "Chad")] CHD = 43,
        [Display(Name = "Chile")] CF = 44,
        [Display(Name = "China")] TD = 45,
        [Display(Name = "Christmas Island")] CL = 46,
        [Display(Name = "Cocos (Keeling) Islands")] CN = 47,
        [Display(Name = "Colombia")] COL = 48,
        [Display(Name = "Comoros")] COM = 49,
        [Display(Name = "Democratic Republic of the Congo (Kinsha")] CO = 50,
        [Display(Name = "Congo, Republic of (Brazzaville)")] KM = 51,
        [Display(Name = "Cook Islands")] CG = 52,
        [Display(Name = "Costa Rica")] CR = 53,
        [Display(Name = "Ivory Coast")] IVC = 54,
        [Display(Name = "Croatia")] CRO = 55,
        [Display(Name = "Cuba")] CUB = 56,
        [Display(Name = "Cyprus")] HR = 57,
        [Display(Name = "Czech Republic")] CU = 58,
        [Display(Name = "Denmark")] CW = 59,
        [Display(Name = "Djibouti")] CY = 60,
        [Display(Name = "Dominica")] CZ = 61,
        [Display(Name = "Dominican Republic")] DK = 62,
        [Display(Name = "East Timor Timor-Leste")] DJ = 63,
        [Display(Name = "Ecuador")] DM = 64,
        [Display(Name = "Egypt")] EGY = 65,
        [Display(Name = "El Salvador")] EC = 66,
        [Display(Name = "Equatorial Guinea")] EG = 67,
        [Display(Name = "Eritrea")] ERI = 68,
        [Display(Name = "Estonia")] EST = 69,
        [Display(Name = "Ethiopia")] ER = 70,
        [Display(Name = "Falkland Islands")] EE = 71,
        [Display(Name = "Faroe Islands")] ET = 72,
        [Display(Name = "Fiji")] FIJ = 73,
        [Display(Name = "Finland")] FIN = 74,
        [Display(Name = "France")] FRA = 75,
        [Display(Name = "French Guiana")] FI = 76,
        [Display(Name = "French Metropolitan")] FR = 77,
        [Display(Name = "French Polynesia")] FRP = 78,
        [Display(Name = "French Southern Territories")] FST = 79,
        [Display(Name = "Gabon")] GAB = 80,
        [Display(Name = "Gambia")] GA = 81,
        [Display(Name = "Georgia")] GM = 82,
        [Display(Name = "Germany")] GE = 83,
        [Display(Name = "Ghana")] DE = 84,
        [Display(Name = "Gibraltar")] GH = 85,
        [Display(Name = "Great Britain")] GI = 86,
        [Display(Name = "Greece ")] GR = 87,
        [Display(Name = "Greenland")] GL = 88,
        [Display(Name = "Grenada")] GD = 89,
        [Display(Name = "Guadeloupe")] GP = 90,
        [Display(Name = "Guam")] GU = 91,
        [Display(Name = "Guatemala")] GT = 92,
        [Display(Name = "Guernsey")] GG = 93,
        [Display(Name = "Guinea")] GN = 94,
        [Display(Name = "Guinea-Bissau")] GW = 95,
        [Display(Name = "Guyana")] GY = 96,
        [Display(Name = "Haiti")] HT = 97,
        [Display(Name = "Heard and Mc Donald Islands")] MCD = 98,
        [Display(Name = "Holy See")] HS = 99,
        [Display(Name = "Honduras")] HN = 100,
        [Display(Name = "Hong Kong")] HOK = 101,
        [Display(Name = "Hungary")] HU = 102,
        [Display(Name = "Iceland")] IS = 103,
        [Display(Name = "India")] IN = 104,
        [Display(Name = "Iran (Islamic Republic of")] IRN = 106,
        [Display(Name = "Iraq")] IQ = 107,
        [Display(Name = "Ireland")] IE = 108,
        [Display(Name = "Isle of Man")] IM = 109,
        [Display(Name = "Israel")] IL = 110,
        [Display(Name = "Italy")] IT = 111,
        [Display(Name = "Jamaica")] JM = 112,
        [Display(Name = "Japan")] JP = 113,
        [Display(Name = "Jersey")] JE = 114,
        [Display(Name = "Jordan")] JO = 115,
        [Display(Name = "Kazakhstan")] KZ = 116,
        [Display(Name = "Kenya")] KE = 117,
        [Display(Name = "Kiribati")] KI = 118,
        [Display(Name = "North Korea")] NK = 119,
        [Display(Name = "South Korea")] SK = 120,
        [Display(Name = "Kosovo")] KW = 121,
        [Display(Name = "Kuwait")] KG = 122,
        [Display(Name = "Kyrgyzstan")] KYR = 123,
        [Display(Name = "Lao, Peoples Democratic Republic")] LV = 124,
        [Display(Name = "Latvia")] LB = 125,
        [Display(Name = "Lebanon")] LS = 126,
        [Display(Name = "Lesotho")] LR = 127,
        [Display(Name = "Liberia")] LY = 128,
        [Display(Name = "Libya")] LI = 129,
        [Display(Name = "Liechtenstein")] LT = 130,
        [Display(Name = "Lithuania")] LU = 131,
        [Display(Name = "Luxembourg")] MO = 132,
        [Display(Name = "Macau")] Macau = 133,
        [Display(Name = "Macedonia, Rep. of")] MG = 134,
        [Display(Name = "Madagascar")] MW = 135,
        [Display(Name = "Malawi")] MY = 136,
        [Display(Name = "Malaysia")] MV = 137,
        [Display(Name = "Maldives")] ML = 138,
        [Display(Name = "Mali")] MT = 139,
        [Display(Name = "Malta")] MLT = 140,
        [Display(Name = "Marshall Islands")] MQ = 141,
        [Display(Name = "Martinique")] MR = 142,
        [Display(Name = "Mauritania")] MU = 143,
        [Display(Name = "Mauritius")] YT = 144,
        [Display(Name = "Mayotte")] MX = 145,
        [Display(Name = "Mexico")] MXC = 146,
        [Display(Name = "Micronesia, Federal States of")] MIC = 147,
        [Display(Name = "Moldova, Republic of")] MC = 148,
        [Display(Name = "Monaco")] MN = 149,
        [Display(Name = "Mongolia")] ME = 150,
        [Display(Name = "Montenegro")] MS = 151,
        [Display(Name = "Montserrat")] MA = 152,
        [Display(Name = "Morocco")] MZ = 153,
        [Display(Name = "Mozambique")] MM = 154,
        [Display(Name = "Myanmar, Burma")] NA = 155,
        [Display(Name = "Namibia")] NR = 156,
        [Display(Name = "Nauru")] NP = 157,
        [Display(Name = "Nepal")] NL = 158,
        [Display(Name = "Netherlands")] NEL = 159,
        [Display(Name = "Netherlands Antilles")] NET = 160,
        [Display(Name = "New Caledonia")] NI = 161,
        [Display(Name = "New Zealand")] NE = 162,
        [Display(Name = "Nicaragua")] NG = 163,
        [Display(Name = "Niger")] NU = 164,
        [Display(Name = "Nigeria")] NIG = 165,
        [Display(Name = "Niue")] NIU = 166,
        [Display(Name = "Norfolk Island")] NO = 167,
        [Display(Name = "Northern Mariana Islands")] OM = 168,
        [Display(Name = "Norway")] PK = 169,
        [Display(Name = "Oman")] PW = 170,
        [Display(Name = "Pakistan")] State = 171,
        [Display(Name = "Palau")] PA = 172,
        [Display(Name = "Palestinian National Authority")] New = 173,
        [Display(Name = "Panama")] PY = 174,
        [Display(Name = "Papua New Guinea")] PE = 175,
        [Display(Name = "Paraguay")] PH = 176,
        [Display(Name = "Peru")] PN = 177,
        [Display(Name = "Philippines")] PL = 178,
        [Display(Name = "Pitcairn Island")] PT = 179,
        [Display(Name = "Poland")] POL = 180,
        [Display(Name = "Portugal")] QA = 181,
        [Display(Name = "Puerto Rico")] RE = 182,
        [Display(Name = "Qatar")] RO = 183,
        [Display(Name = "Reunion Island")] RUN = 184,
        [Display(Name = "Romania")] RW = 185,
        [Display(Name = "Russian Federation")] RUS = 186,
        [Display(Name = "Rwanda")] RWA = 187,
        [Display(Name = "Saint Kitts and Nevis")] SKN = 188,
        [Display(Name = "Saint Lucia")] SL = 189,
        [Display(Name = "Saint Vincent and the Grenadines")] SVG = 190,
        [Display(Name = "Samoa")] Pierre = 191,
        [Display(Name = "San Marino")] Vincent = 192,
        [Display(Name = "Sao Tome and PrÃ­ncipe")] WS = 193,
        [Display(Name = "Saudi Arabia")] SA = 194,
        [Display(Name = "Senegal")] Tome = 195,
        [Display(Name = "Serbia")] SER = 196,
        [Display(Name = "Seychelles")] SN = 197,
        [Display(Name = "Sierra Leone")] RS = 198,
        [Display(Name = "Singapore")] SC = 199,
        [Display(Name = "Slovakia (Slovak Republic)")] SLO = 200,
        [Display(Name = "Slovenia")] SG = 201,
        [Display(Name = "Solomon Islands")] SOLO = 202,
        [Display(Name = "Somalia")] Soma = 203,
        [Display(Name = "South Africa")] SI = 204,
        [Display(Name = "South Georgia and South Sandwich Islands")] SGS = 205,
        [Display(Name = "South Sudan")] SO = 206,
        [Display(Name = "Spain")] SPN = 207,
        [Display(Name = "Sri Lanka")] Georgia = 208,
        [Display(Name = "Saint Helena")] SAH = 209,
        [Display(Name = "St. Pierre and Miquelon")] ES = 210,
        [Display(Name = "Sudan")] SUD = 211,
        [Display(Name = "Suriname")] SD = 212,
        [Display(Name = "Svalbard and Jan Mayen Islands")] SR = 213,
        [Display(Name = "Swaziland")] SWA = 214,
        [Display(Name = "Sweden")] SZ = 215,
        [Display(Name = "Switzerland")] SE = 216,
        [Display(Name = "\"Syria, Syrian Arab Republic\" ")] CH = 217,
        [Display(Name = "Taiwan (Republic of China)")] Arab = 218,
        [Display(Name = "Tajikistan")] Province = 219,
        [Display(Name = "Tanzania")] TJ = 220,
        [Display(Name = "Thailand")] United = 221,
        [Display(Name = "Tibet")] TH = 222,
        [Display(Name = "Timor-Leste (East Timor)")] TL = 223,
        [Display(Name = "Togo")] TG = 224,
        [Display(Name = "Tokelau")] TK = 225,
        [Display(Name = "Tonga")] TO = 226,
        [Display(Name = "Trinidad and Tobago")] and = 227,
        [Display(Name = "Tunisia")] TN = 228,
        [Display(Name = "Turkey")] TR = 229,
        [Display(Name = "Turkmenistan")] TM = 230,
        [Display(Name = "Turks and Caicos Islands ")] Turks = 231,
        [Display(Name = "Tuvalu")] TV = 232,
        [Display(Name = "Uganda")] UG = 233,
        [Display(Name = "Ukraine")] UA = 234,
        [Display(Name = "United Arab Emirates")] AE = 235,
        [Display(Name = "United Kingdom")] Kingdom = 236,
        [Display(Name = "United States")] States = 237,
        [Display(Name = "U.S. Minor Outlying Islands")] UsState = 238,
        [Display(Name = "Uruguay")] UY = 239,
        [Display(Name = "Uzbekistan")] UZ = 240,
        [Display(Name = "Vanuatu")] VU = 241,
        [Display(Name = "Vatican City State (Holy See)")] VAT = 242,
        [Display(Name = "Venezuela")] Ven = 243,
        [Display(Name = "Vietnam")] VIT = 244,
        [Display(Name = "Virgin Islands (British)")] VRG = 245,
        [Display(Name = "Virgin Islands (U.S.)")] VIS = 246,
        [Display(Name = "Wallis and Futuna Islands")] WAL = 247,
        [Display(Name = "Western Sahara")] YE = 248,
        [Display(Name = "Yemen")] ZM = 249,
        [Display(Name = "\"Zaire (see Congo, Democratic Peoples Re")] ZW = 250,
        [Display(Name = "Zambia")] ZAM = 251,
        [Display(Name = "Zimbabwe")] ZIM = 252

    }
    //public enum Country
    //{
    //    [Display(Name = "Afghanistan")] AF = 1,
    //    [Display(Name = "Albania")] AX = 2,
    //    [Display(Name = "Algeria")] AL = 3,
    //    //[Display(Name = "Algeria")] DZ = 4,
    //    [Display(Name = "American Samoa")] AS = 4,
    //    [Display(Name = "Andorra")] AD = 5,
    //    [Display(Name = "Angola")] AO = 6,
    //    [Display(Name = "Anguilla")] AI = 7,
    //    [Display(Name = "Antarctica")] AQ = 8,
    //    [Display(Name = "Antigua and Barbuda")] AG = 9,
    //    [Display(Name = "Argentina")] AR = 10,
    //    [Display(Name = "Armenia")] AM = 11,
    //    [Display(Name = "Aruba")] AW = 12,
    //    [Display(Name = "Ascension Island")] ASC = 13,
    //    [Display(Name = "Australia")] AU = 14,
    //    [Display(Name = "Austria")] AT = 15,
    //    [Display(Name = "Azerbaijan")] AZ = 16,
    //    [Display(Name = "Bahamas")] BS = 17,
    //    [Display(Name = "Bahrain")] BH = 18,
    //    [Display(Name = "Bangladesh")] BD = 19,
    //    [Display(Name = "Barbados")] BB = 20,
    //    [Display(Name = "Belarus")] BY = 21,
    //    [Display(Name = "Belgium")] BE = 22,
    //    [Display(Name = "Belize")] BZ = 23,
    //    [Display(Name = "Benin")] BJ = 24,
    //    [Display(Name = "Bermuda")] BM = 25,
    //    [Display(Name = "Bhutan")] BT = 26,
    //    [Display(Name = "Bolivia")] BO = 27,
    //    [Display(Name = "Bosnia and Herzegovina")] BA = 28,
    //    [Display(Name = "Botswana")] BW = 29,
    //    [Display(Name = "Bouvet Island")] BV = 30,
    //    [Display(Name = "Brazil")] BR = 31,
    //    //[Display(Name = "Bonaire, Sint Eustatius and Saba")] BQ = 28,
    //    [Display(Name = "British Indian Ocean Territory")] IO = 32,
    //    [Display(Name = "Brunei Darussalam")] BN = 33,
    //    [Display(Name = "Bulgaria")] BG = 34,
    //    [Display(Name = "Burkina Faso")] BF = 35,
    //    [Display(Name = "Burundi")] BI = 36,
    //    [Display(Name = "Cambodia")] KH = 37,
    //    [Display(Name = "Cameroon")] CM = 38,
    //    [Display(Name = "Canada")] CA = 39,
    //    [Display(Name = "Cabo Verde")] CV = 40,
    //    [Display(Name = "Cayman Islands")] KY = 41,
    //    [Display(Name = "Central African Republic")] CF = 42,
    //    [Display(Name = "Chad")] TD = 43,
    //    [Display(Name = "Chile")] CL = 44,
    //    [Display(Name = "China")] CN = 45,
    //    [Display(Name = "Christmas Island")] CX = 46,
    //    [Display(Name = "Cocos (Keeling) Islands")] CC = 47,
    //    [Display(Name = "Colombia")] CO = 48,
    //    [Display(Name = "Comoros")] KM = 49,
    //    [Display(Name = "Congo")] CG = 51,
    //    [Display(Name = "Congo (Democratic Republic of the)")] CD = 52,
    //    [Display(Name = "Cook Islands")] CK = 53,
    //    [Display(Name = "Costa Rica")] CR = 54,
    //    [Display(Name = "Côte d'Ivoire")] CI = 55,
    //    [Display(Name = "Croatia")] HR = 56,
    //    [Display(Name = "Cuba")] CU = 57,
    //    [Display(Name = "Curaçao")] CW = 58,
    //    [Display(Name = "Cyprus")] CY = 59,
    //    [Display(Name = "Czechia")] CZ = 60,
    //    [Display(Name = "Denmark")] DK = 61,
    //    [Display(Name = "Djibouti")] DJ = 62,
    //    [Display(Name = "Dominica")] DM = 63,
    //    [Display(Name = "Dominican Republic")] DO = 64,
    //    [Display(Name = "Ecuador")] EC = 65,
    //    [Display(Name = "Egypt")] EG = 66,
    //    [Display(Name = "El Salvador")] SV = 67,
    //    [Display(Name = "Equatorial Guinea")] GQ = 68,
    //    [Display(Name = "Eritrea")] ER = 69,
    //    [Display(Name = "Estonia")] EE = 70,
    //    [Display(Name = "Ethiopia")] ET = 71,
    //    [Display(Name = "Falkland Islands (Malvinas)")] FK = 72,
    //    [Display(Name = "Faroe Islands")] FO = 73,
    //    [Display(Name = "Fiji")] FJ = 74,
    //    [Display(Name = "Finland")] FI = 75,
    //    [Display(Name = "France")] FR = 76,
    //    [Display(Name = "French Guiana")] GF = 77,
    //    [Display(Name = "French Polynesia")] PF = 78,
    //    [Display(Name = "French Southern Territories")] TF = 79,
    //    [Display(Name = "Gabon")] GA = 80,
    //    [Display(Name = "Gambia")] GM = 81,
    //    [Display(Name = "Georgia")] GE = 82,
    //    [Display(Name = "Germany")] DE = 83,
    //    [Display(Name = "Ghana")] GH = 84,
    //    [Display(Name = "Gibraltar")] GI = 85,
    //    [Display(Name = "Greece")] GR = 86,
    //    [Display(Name = "Greenland")] GL = 87,
    //    [Display(Name = "Grenada")] GD = 88,
    //    [Display(Name = "Guadeloupe")] GP = 89,
    //    [Display(Name = "Guam")] GU = 90,
    //    [Display(Name = "Guatemala")] GT = 91,
    //    [Display(Name = "Guernsey")] GG = 92,
    //    [Display(Name = "Guinea")] GN = 93,
    //    [Display(Name = "Guinea-Bissau")] GW = 94,
    //    [Display(Name = "Guyana")] GY = 95,
    //    [Display(Name = "Haiti")] HT = 96,
    //    [Display(Name = "Heard Island and McDonald Islands")] HM = 97,
    //    [Display(Name = "Holy See")] VA = 98,
    //    [Display(Name = "Honduras")] HN = 99,
    //    [Display(Name = "Hong Kong")] HK = 100,
    //    [Display(Name = "Hungary")] HU = 101,
    //    [Display(Name = "Iceland")] IS = 102,
    //    [Display(Name = "India")] IN = 103,
    //    [Display(Name = "Indonesia")] ID = 104,
    //    [Display(Name = "Iran (Islamic Republic of)")] IR = 105,
    //    [Display(Name = "Iraq")] IQ = 106,
    //    [Display(Name = "Ireland")] IE = 107,
    //    [Display(Name = "Isle of Man")] IM = 108,
    //    [Display(Name = "Israel")] IL = 109,
    //    [Display(Name = "Italy")] IT = 110,
    //    [Display(Name = "Jamaica")] JM = 111,
    //    [Display(Name = "Japan")] JP = 112,
    //    [Display(Name = "Jersey")] JE = 113,
    //    [Display(Name = "Jordan")] JO = 114,
    //    [Display(Name = "Kazakhstan")] KZ = 115,
    //    [Display(Name = "Kenya")] KE = 116,
    //    [Display(Name = "Kiribati")] KI = 117,
    //    [Display(Name = "Korea (Democratic People's Republic of)")] KP = 118,
    //    [Display(Name = "Korea (Republic of)")] KR = 119,
    //    [Display(Name = "Kuwait")] KW = 120,
    //    [Display(Name = "Kyrgyzstan")] KG = 121,
    //    [Display(Name = "Lao People's Democratic Republic")] LA = 122,
    //    [Display(Name = "Latvia")] LV = 123,
    //    [Display(Name = "Lebanon")] LB = 124,
    //    [Display(Name = "Lesotho")] LS = 125,
    //    [Display(Name = "Liberia")] LR = 126,
    //    [Display(Name = "Libya")] LY = 127,
    //    [Display(Name = "Liechtenstein")] LI = 128,
    //    [Display(Name = "Lithuania")] LT = 129,
    //    [Display(Name = "Luxembourg")] LU = 130,
    //    [Display(Name = "Macao")] MO = 131,
    //    [Display(Name = "Macedonia (the former Yugoslav Republic of)")] MK = 132,
    //    [Display(Name = "Madagascar")] MG = 133,
    //    [Display(Name = "Malawi")] MW = 134,
    //    [Display(Name = "Malaysia")] MY = 135,
    //    [Display(Name = "Maldives")] MV = 136,
    //    [Display(Name = "Mali")] ML = 137,
    //    [Display(Name = "Malta")] MT = 138,
    //    [Display(Name = "Marshall Islands")] MH = 139,
    //    [Display(Name = "Martinique")] MQ = 140,
    //    [Display(Name = "Mauritania")] MR = 141,
    //    [Display(Name = "Mauritius")] MU = 142,
    //    [Display(Name = "Mayotte")] YT = 143,
    //    [Display(Name = "Mexico")] MX = 144,
    //    [Display(Name = "Micronesia (Federated States of)")] FM = 145,
    //    [Display(Name = "Moldova (Republic of)")] MD = 146,
    //    [Display(Name = "Monaco")] MC = 147,
    //    [Display(Name = "Mongolia")] MN = 148,
    //    [Display(Name = "Montenegro")] ME = 149,
    //    [Display(Name = "Montserrat")] MS = 150,
    //    [Display(Name = "Morocco")] MA = 151,
    //    [Display(Name = "Mozambique")] MZ = 152,
    //    [Display(Name = "Myanmar")] MM = 153,
    //    [Display(Name = "Namibia")] NA = 154,
    //    [Display(Name = "Nauru")] NR = 155,
    //    [Display(Name = "Nepal")] NP = 156,
    //    [Display(Name = "Netherlands")] NL = 157,
    //    [Display(Name = "New Caledonia")] NC = 158,
    //    [Display(Name = "New Zealand")] NZ = 159,
    //    [Display(Name = "Nicaragua")] NI = 160,
    //    [Display(Name = "Niger")] NE = 161,
    //    [Display(Name = "Nigeria")] NG = 162,
    //    [Display(Name = "Niue")] NU = 163,
    //    [Display(Name = "Norfolk Island")] NF = 164,
    //    [Display(Name = "Northern Mariana Islands")] MP = 165,
    //    [Display(Name = "Norway")] NO = 166,
    //    [Display(Name = "Oman")] OM = 167,
    //    [Display(Name = "Pakistan")] PK = 168,
    //    [Display(Name = "Palau")] PW = 169,
    //    [Display(Name = "Palestine, State of")] PS = 170,
    //    [Display(Name = "Panama")] PA = 171,
    //    [Display(Name = "Papua New Guinea")] PG = 172,
    //    [Display(Name = "Paraguay")] PY = 173,
    //    [Display(Name = "Peru")] PE = 174,
    //    [Display(Name = "Philippines")] PH = 175,
    //    [Display(Name = "Pitcairn")] PN = 176,
    //    [Display(Name = "Poland")] PL = 177,
    //    [Display(Name = "Portugal")] PT = 178,
    //    [Display(Name = "Puerto Rico")] PR = 179,
    //    [Display(Name = "Qatar")] QA = 180,
    //    [Display(Name = "Réunion")] RE = 181,
    //    [Display(Name = "Romania")] RO = 182,
    //    [Display(Name = "Russian Federation")] RU = 183,
    //    [Display(Name = "Rwanda")] RW = 184,
    //    [Display(Name = "Saint Barthélemy")] BL = 185,
    //    [Display(Name = "Saint Helena, Ascension and Tristan da Cunha")] SH = 186,
    //    [Display(Name = "Saint Kitts and Nevis")] KN = 187,
    //    [Display(Name = "Saint Lucia")] LC = 188,
    //    [Display(Name = "Saint Martin (French part)")] MF = 189,
    //    [Display(Name = "Saint Pierre and Miquelon")] PM = 190,
    //    [Display(Name = "Saint Vincent and the Grenadines")] VC = 191,
    //    [Display(Name = "Samoa")] WS = 192,
    //    [Display(Name = "San Marino")] SM = 193,
    //    [Display(Name = "Sao Tome and Principe")] ST = 194,
    //    [Display(Name = "Saudi Arabia")] SA = 195,
    //    [Display(Name = "Senegal")] SN = 196,
    //    [Display(Name = "Serbia")] RS = 197,
    //    [Display(Name = "Seychelles")] SC = 198,
    //    [Display(Name = "Sierra Leone")] SL = 199,
    //    [Display(Name = "Singapore")] SG = 200,
    //    [Display(Name = "Sint Maarten (Dutch part)")] SX = 201,
    //    [Display(Name = "Slovakia")] SK = 202,
    //    [Display(Name = "Slovenia")] SI = 203,
    //    [Display(Name = "Solomon Islands")] SB = 204,
    //    [Display(Name = "Somalia")] SO = 205,
    //    [Display(Name = "South Africa")] ZA = 206,
    //    [Display(Name = "South Georgia and the South Sandwich Islands")] GS = 207,
    //    [Display(Name = "South Sudan")] SS = 208,
    //    [Display(Name = "Spain")] ES = 209,
    //    [Display(Name = "Sri Lanka")] LK = 210,
    //    [Display(Name = "Sudan")] SD = 211,
    //    [Display(Name = "Suriname")] SR = 212,
    //    [Display(Name = "Svalbard and Jan Mayen")] SJ = 213,
    //    [Display(Name = "Swaziland")] SZ = 214,
    //    [Display(Name = "Sweden")] SE = 215,
    //    [Display(Name = "Switzerland")] CH = 216,
    //    [Display(Name = "Syrian Arab Republic")] SY = 217,
    //    [Display(Name = "Taiwan, Province of China[a]")] TW = 218,
    //    [Display(Name = "Tajikistan")] TJ = 219,
    //    [Display(Name = "Tanzania, United Republic of")] TZ = 220,
    //    [Display(Name = "Thailand")] TH = 221,
    //    [Display(Name = "Timor-Leste")] TL = 222,
    //    [Display(Name = "Togo")] TG = 223,
    //    [Display(Name = "Tokelau")] TK = 224,
    //    [Display(Name = "Tonga")] TO = 225,
    //    [Display(Name = "Trinidad and Tobago")] TT = 226,
    //    [Display(Name = "Tunisia")] TN = 227,
    //    [Display(Name = "Turkey")] TR = 228,
    //    [Display(Name = "Turkmenistan")] TM = 229,
    //    [Display(Name = "Turks and Caicos Islands")] TC = 230,
    //    [Display(Name = "Tuvalu")] TV = 231,
    //    [Display(Name = "Uganda")] UG = 232,
    //    [Display(Name = "Ukraine")] UA = 233,
    //    [Display(Name = "United Arab Emirates")] AE = 234,
    //    [Display(Name = "United Kingdom of Great Britain and Northern Ireland")] GB = 235,
    //    [Display(Name = "United States of America")] US = 236,
    //    [Display(Name = "United States Minor Outlying Islands")] UM = 237,
    //    [Display(Name = "Uruguay")] UY = 238,
    //    [Display(Name = "Uzbekistan")] UZ = 239,
    //    [Display(Name = "Vanuatu")] VU = 240,
    //    [Display(Name = "Venezuela (Bolivarian Republic of)")] VE = 241,
    //    [Display(Name = "Viet Nam")] VN = 242,
    //    [Display(Name = "Virgin Islands (British)")] VG = 243,
    //    [Display(Name = "Virgin Islands (U.S.)")] VI = 244,
    //    [Display(Name = "Wallis and Futuna")] WF = 245,
    //    [Display(Name = "Western Sahara")] EH = 246,
    //    [Display(Name = "Yemen")] YE = 247,
    //    [Display(Name = "Zambia")] ZM = 248,
    //    [Display(Name = "Zimbabwe")] ZW = 249,
    //}
}
